apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nats
  name: nats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nats
    spec:
      containers:
      - image: nats
        name: nats
        ports:
          - containerPort: 4222
          - containerPort: 8222
        args: ["-m", "8222"] # Habilitar el puerto de monitoreo
        
        resources: {}
status: {}
