apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nats
  name: nats
spec:
  ports:
  - name: "4222"
    port: 4222
    protocol: TCP
    targetPort: 4222
  - port: 8222
    targetPort: 8222
    name: monitoring
  selector:
    app: nats
  type: ClusterIP
status:
  loadBalancer: {}
